"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { OperationsHeader } from "@/components/ui/OperationsHeader";
import { MetricCard } from "@/components/ui/MetricCard";
import { LoadingState } from "@/components/ui/LoadingState";
import { Notice } from "@/components/ui/Notice";
import { Icon } from "@/components/ui/Icon";

type Customer={id:string;name:string;phone:string;address?:string|null;segment?:string|null;tags?:string|null;satisfaction?:number|null;nextContactAt?:string|null;lastContactAt?:string|null;owner?:{name:string}|null;machines:{id:string;model:string;status:string}[];_count:{activities:number;tickets:number}};
const date=(v?:string|null)=>v?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short"}).format(new Date(v)):"—";
export default function CustomersPage(){
 const[data,setData]=useState<Customer[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[q,setQ]=useState("");const[segment,setSegment]=useState("ALL");
 const load=useCallback(async()=>{setLoading(true);try{const params=new URLSearchParams();if(q.trim())params.set("q",q.trim());if(segment!=="ALL")params.set("segment",segment);const r=await fetch(`/api/crm/customers?${params}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message);setData(j.data.customers);}catch(e){setError(e instanceof Error?e.message:"Không tải được CRM");}finally{setLoading(false);}},[q,segment]);useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t);},[load]);
 const stats=useMemo(()=>({total:data.length,vip:data.filter(c=>c.segment==="VIP").length,follow:data.filter(c=>Boolean(c.nextContactAt)).length,risk:data.filter(c=>(c.satisfaction||5)<=2||c._count.tickets>0).length}),[data]);
 return <main className="min-h-screen"><OperationsHeader title="Khách hàng 360°" subtitle="Một hồ sơ thống nhất cho máy, chăm sóc, dịch vụ và khiếu nại"/><div className="page-container space-y-6">{error&&<Notice kind="error">{error}</Notice>}<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Khách hàng" value={stats.total} icon="users" tone="emerald"/><MetricCard label="Khách VIP" value={stats.vip} icon="star" tone="violet"/><MetricCard label="Có lịch liên hệ" value={stats.follow} icon="phone" tone="amber"/><MetricCard label="Cần quan tâm" value={stats.risk} icon="alert" tone="rose"/></section><section className="surface-card"><div className="data-toolbar"><div className="relative min-w-[260px] flex-1 max-w-xl"><Icon name="search" size={18} className="pointer-events-none absolute left-3 top-3.5 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên, số điện thoại hoặc địa chỉ" className="pl-10"/></div><select value={segment} onChange={e=>setSegment(e.target.value)} className="max-w-48"><option value="ALL">Tất cả phân khúc</option><option value="STANDARD">Tiêu chuẩn</option><option value="VIP">VIP</option><option value="AT_RISK">Có nguy cơ</option><option value="INTERNAL">Nội bộ</option></select></div>{loading?<LoadingState label="Đang tìm khách hàng..."/>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr>{["Khách hàng","Phân khúc","Thiết bị","Tương tác","Ticket","CSKH phụ trách","Liên hệ tiếp","Đánh giá",""].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{data.map(c=><tr key={c.id}><td className="p-3"><strong>{c.name}</strong><div><a href={`tel:${c.phone}`} className="text-emerald-700">{c.phone}</a></div><div className="max-w-xs truncate text-xs text-slate-500">{c.address||"Chưa có địa chỉ"}</div></td><td className="p-3"><span className={`status-badge ${c.segment==="VIP"?"badge-violet":c.segment==="AT_RISK"?"badge-rose":"badge-slate"}`}>{c.segment||"STANDARD"}</span></td><td className="p-3"><strong>{c.machines.length}</strong><div className="text-xs text-slate-500">{c.machines.slice(0,2).map(m=>m.id).join(", ")}</div></td><td className="p-3 font-bold">{c._count.activities}</td><td className="p-3 font-bold">{c._count.tickets}</td><td className="p-3">{c.owner?.name||"Chưa giao"}</td><td className="p-3">{date(c.nextContactAt)}</td><td className="p-3 font-black">{c.satisfaction?`${c.satisfaction}/5`:"—"}</td><td className="p-3"><Link href={`/cskh/customers/${c.id}`} className="icon-button" title="Mở hồ sơ"><Icon name="chevron-right" size={18}/></Link></td></tr>)}{!data.length&&<tr><td colSpan={9} className="p-10 text-center text-slate-500">Không tìm thấy khách hàng phù hợp.</td></tr>}</tbody></table></div>}</section></div></main>;
}
