"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import InteractiveMap, { type MapMarker } from "@/components/maps/InteractiveMap";
import { OperationsHeader } from "@/components/ui/OperationsHeader";
import { Icon } from "@/components/ui/Icon";
import { LoadingState } from "@/components/ui/LoadingState";
import { Notice } from "@/components/ui/Notice";

type DealerType = "commercial" | "service" | "freelancer" | "advanced";
type Dealer = { id: string; dealerCode: string; name: string; phone: string; address?: string | null; province?: string | null; services?: string | null; technicianCount?: number | null; rating?: number | null; registrationType?: string | null; lat?: number | null; lng?: number | null; portraitPhoto?: string | null; storePhoto?: string | null; warehousePhoto?: string | null; status: string };
const META: Record<DealerType, { label: string; color: string; glyph: MapMarker["glyph"]; icon: "store"|"settings"|"wrench"|"star" }> = {
  commercial: { label: "Đại lý thương mại", color: "#d97706", glyph: "store", icon: "store" },
  service: { label: "Đại lý dịch vụ", color: "#2563eb", glyph: "wrench", icon: "settings" },
  freelancer: { label: "CTV kỹ thuật", color: "#e11d48", glyph: "user", icon: "wrench" },
  advanced: { label: "CTV năng lực cao", color: "#059669", glyph: "star", icon: "star" },
};
function typeOf(dealer: Dealer): DealerType { const skills = (dealer.services || "").split(",").filter(Boolean).length; if (dealer.dealerCode.includes("-CTV-")) return skills >= 3 ? "advanced" : "freelancer"; return (dealer.technicianCount || 0) > 0 ? "service" : "commercial"; }

export default function DealerMapPage() {
  const [dealers, setDealers] = useState<Dealer[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [search, setSearch] = useState(""); const [kind, setKind] = useState<DealerType | "">(""); const [province, setProvince] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/dealers", { cache: "no-store" }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Không tải được đại lý."); setDealers((result.data || []).filter((d: Dealer) => d.status === "APPROVED")); } catch (value) { setError(value instanceof Error ? value.message : "Không tải được dữ liệu."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const provinces = useMemo(() => [...new Set(dealers.map((d) => d.province).filter(Boolean) as string[])].sort(), [dealers]);
  const filtered = useMemo(() => dealers.filter((d) => { const text = `${d.dealerCode} ${d.name} ${d.phone} ${d.services || ""} ${d.address || ""}`.toLowerCase(); return (!search || text.includes(search.toLowerCase())) && (!kind || typeOf(d) === kind) && (!province || d.province === province); }), [dealers, search, kind, province]);
  const located = filtered.filter((d) => d.lat != null && d.lng != null);
  const selected = dealers.find((d) => d.id === selectedId) || null;
  const markers: MapMarker[] = located.map((dealer) => { const meta = META[typeOf(dealer)]; return { id: dealer.id, lat: dealer.lat!, lng: dealer.lng!, title: dealer.name, subtitle: `${dealer.dealerCode} · ${dealer.phone}`, color: meta.color, glyph: meta.glyph }; });

  return <main className="min-h-screen bg-slate-50/70"><OperationsHeader title="Bản đồ mạng lưới đại lý" subtitle="Quan sát năng lực kỹ thuật và vùng phục vụ" actions={<button type="button" onClick={load} className="icon-button" title="Tải lại"><Icon name="refresh" size={18}/></button>}/><section className="mx-auto max-w-[1480px] space-y-4 p-3 sm:p-5">{error && <Notice kind="error">{error}</Notice>}
    <div className="grid gap-3 md:grid-cols-[1fr_210px_210px_auto] surface-card p-3"><label className="relative"><Icon name="search" size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm mã, tên, SĐT, địa chỉ hoặc năng lực" className="pl-11"/></label><select value={province} onChange={(e) => setProvince(e.target.value)}><option value="">Tất cả tỉnh</option>{provinces.map((p) => <option key={p}>{p}</option>)}</select><select value={kind} onChange={(e) => setKind(e.target.value as DealerType|"")}><option value="">Tất cả loại hình</option>{Object.entries(META).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select><button type="button" onClick={() => { setSearch(""); setProvince(""); setKind(""); }} className="btn-secondary"><Icon name="x" size={17}/> Xóa lọc</button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{(Object.keys(META) as DealerType[]).map((key) => <button type="button" key={key} onClick={() => setKind(kind === key ? "" : key)} className={`metric-card text-left ${kind === key ? "ring-2 ring-emerald-500" : ""}`}><span className="metric-icon" style={{ color: META[key].color, background: `${META[key].color}18` }}><Icon name={META[key].icon}/></span><div><p className="metric-label">{META[key].label}</p><p className="metric-value">{dealers.filter((d) => typeOf(d) === key).length}</p></div></button>)}</div>
    {loading ? <LoadingState label="Đang tải mạng lưới đại lý..."/> : <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_370px]"><InteractiveMap markers={markers} activeId={selectedId} onSelect={setSelectedId} height={690}/><aside className="surface-card min-h-[320px] p-5 xl:h-[690px] xl:overflow-y-auto">{selected ? <DealerDetail dealer={selected} onClose={() => setSelectedId(null)}/> : <div className="flex h-full min-h-[300px] flex-col justify-center text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-blue-700"><Icon name="store" size={30}/></span><h2 className="mt-4 text-xl font-extrabold">Chọn một đại lý</h2><p className="mx-auto mt-2 max-w-xs text-sm leading-6 text-slate-500">Xem kỹ năng, số kỹ thuật viên, rating, ảnh cơ sở và gọi trực tiếp.</p><p className="mx-auto mt-5 rounded-xl bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800"><strong>{dealers.filter((d) => d.lat == null || d.lng == null).length}</strong> đại lý chưa có tọa độ GPS.</p></div>}</aside></div>}
  </section></main>;
}
function DealerDetail({ dealer, onClose }: { dealer: Dealer; onClose: () => void }) { const meta = META[typeOf(dealer)]; return <div><div className="flex items-start justify-between gap-3"><div><span className="status-pill" style={{ color: meta.color, background: `${meta.color}18` }}>{meta.label}</span><h2 className="mt-3 text-xl font-extrabold">{dealer.name}</h2><p className="mt-1 text-sm font-bold text-blue-700">{dealer.dealerCode}</p></div><button type="button" className="icon-button" onClick={onClose}><Icon name="x" size={18}/></button></div><div className="mt-5 space-y-4"><Info icon="phone" label="Số điện thoại" value={dealer.phone}/><Info icon="map-pin" label="Địa chỉ" value={[dealer.address, dealer.province].filter(Boolean).join(", ") || "—"}/><Info icon="users" label="Kỹ thuật viên" value={`${dealer.technicianCount || 0} người`}/><Info icon="star" label="Đánh giá" value={`${dealer.rating ?? 5}/5`}/><Info icon="wrench" label="Năng lực" value={dealer.services || "Chưa cập nhật"}/></div><div className="mt-5 grid grid-cols-3 gap-2">{[[dealer.portraitPhoto,"Chân dung"],[dealer.storePhoto,"Cửa hàng"],[dealer.warehousePhoto,"Kho"]].map(([url,label]) => url ? <a key={label} href={url as string} target="_blank" className="btn-secondary px-2 text-xs"><Icon name="camera" size={15}/>{label}</a> : null)}</div><a href={`tel:${dealer.phone}`} className="btn-primary mt-5 flex items-center justify-center gap-2 px-4 py-3 font-bold text-white"><Icon name="phone" size={18}/> Gọi đại lý</a></div>; }
function Info({ icon, label, value }: { icon: "phone"|"map-pin"|"users"|"star"|"wrench"; label: string; value: string }) { return <div className="flex gap-3"><span className="mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><Icon name={icon} size={17}/></span><div><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-0.5 text-sm font-semibold text-slate-900">{value}</p></div></div>; }
