"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { OperationsHeader } from "@/components/ui/OperationsHeader";
import { LoadingState } from "@/components/ui/LoadingState";
import { Notice } from "@/components/ui/Notice";
import { Icon } from "@/components/ui/Icon";

type Log={id:string;userId?:string|null;action:string;target?:string|null;detail?:string|null;ipAddress?:string|null;userAgent?:string|null;requestId?:string|null;createdAt:string};
const date=(v:string)=>new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"medium"}).format(new Date(v));
export default function AuditLogsPage(){const[data,setData]=useState<Log[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[q,setQ]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/admin-logs",{cache:"no-store"});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message);setData(j.data);}catch(e){setError(e instanceof Error?e.message:"Không tải được nhật ký");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const visible=useMemo(()=>{const key=q.trim().toLowerCase();return key?data.filter(x=>[x.action,x.target,x.userId,x.ipAddress,x.detail].some(v=>v?.toLowerCase().includes(key))):data;},[data,q]);
 return <main className="min-h-screen"><OperationsHeader title="Nhật ký hệ thống" subtitle="Theo dõi thao tác quản trị, IP, thiết bị và dữ liệu thay đổi" actions={<button type="button" onClick={load} className="icon-button"><Icon name="refresh" size={18}/></button>}/><div className="page-container space-y-6">{error&&<Notice kind="error">{error}</Notice>}<section className="surface-card"><div className="data-toolbar"><div className="relative min-w-[280px] max-w-xl flex-1"><Icon name="search" size={18} className="absolute left-3 top-3.5 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm hành động, mục tiêu, IP hoặc nội dung" className="pl-10"/></div><span className="status-badge badge-slate">{visible.length} bản ghi</span></div>{loading?<LoadingState label="Đang tải nhật ký..."/>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr>{["Thời gian","Hành động","Mục tiêu","Người dùng","IP","Chi tiết"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{visible.map(log=><tr key={log.id}><td className="p-3 whitespace-nowrap">{date(log.createdAt)}</td><td className="p-3"><span className="status-badge badge-blue">{log.action}</span></td><td className="p-3 font-bold">{log.target||"—"}</td><td className="p-3 text-xs">{log.userId||"Hệ thống"}</td><td className="p-3 text-xs">{log.ipAddress||"—"}</td><td className="max-w-xl p-3"><details><summary className="cursor-pointer font-bold text-emerald-700">Xem dữ liệu</summary><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-3 text-xs text-slate-100">{log.detail||"Không có chi tiết"}</pre></details></td></tr>)}{!visible.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-500">Không có nhật ký phù hợp.</td></tr>}</tbody></table></div>}</section></div></main>}
