"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { OperationsHeader } from "@/components/ui/OperationsHeader";
import { LoadingState } from "@/components/ui/LoadingState";
import { Notice } from "@/components/ui/Notice";
import { Icon } from "@/components/ui/Icon";
import { StatusBadge } from "@/components/ui/StatusBadge";

type Dealer = { id: string; dealerCode: string; name: string; phone: string; email?: string | null; representativeName?: string | null; companyName?: string | null; registrationType?: string | null; province?: string | null; address?: string | null; services?: string | null; technicianCount?: number | null; serviceArea?: string | null; taxCode?: string | null; citizenId?: string | null; bankAccount?: string | null; accountHolder?: string | null; bankName?: string | null; status: string; portraitPhoto?: string | null; storePhoto?: string | null; warehousePhoto?: string | null; serviceOrders: { id: string; orderCode: string; serviceType: string; status: string; customerName: string; createdAt: string }[]; supportTickets: { id: string; ticketCode: string; subject: string; status: string; createdAt: string }[]; paymentBatches: { id: string; batchCode: string; status: string; netAmount: number; createdAt: string }[] };

export default function DealerDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<Dealer | null>(null);
  const [form, setForm] = useState<Record<string, string | number>>( {} );
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/dealers/${id}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message); setData(result.data); const dealer = result.data as Dealer; setForm({ dealerCode: dealer.dealerCode, name: dealer.name, phone: dealer.phone, email: dealer.email || "", representativeName: dealer.representativeName || "", companyName: dealer.companyName || "", registrationType: dealer.registrationType || "", province: dealer.province || "", address: dealer.address || "", services: dealer.services || "", technicianCount: dealer.technicianCount || 0, serviceArea: dealer.serviceArea || "", taxCode: dealer.taxCode || "", citizenId: dealer.citizenId || "", bankAccount: dealer.bankAccount || "", accountHolder: dealer.accountHolder || "", bankName: dealer.bankName || "" }); } catch (caught) { setNotice({ kind: "error", text: caught instanceof Error ? caught.message : "Không tải được đại lý" }); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setNotice(null); try { const response = await fetch(`/api/dealers/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message); setNotice({ kind: "success", text: result.message }); await load(); } catch (caught) { setNotice({ kind: "error", text: caught instanceof Error ? caught.message : "Không lưu được hồ sơ" }); } finally { setSaving(false); } }
  const field = (name: string, label: string, type = "text") => <label><span className="mb-1 block text-sm font-bold">{label}</span><input type={type} value={String(form[name] ?? "")} onChange={(event) => setForm({ ...form, [name]: event.target.value })}/></label>;

  return <main className="min-h-screen"><OperationsHeader title={data ? `${data.dealerCode} · ${data.name}` : "Chi tiết đại lý"} subtitle="Thông tin đăng ký, mã CRM, tài khoản, lệnh và đối soát" actions={<Link href="/admin/dealers" className="btn-secondary"><Icon name="store" size={16}/>Danh sách đại lý</Link>}/><div className="page-container space-y-6">{notice && <Notice kind={notice.kind}>{notice.text}</Notice>}{loading && !data ? <LoadingState label="Đang tải hồ sơ đại lý..."/> : data && <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="surface-card p-4"><p className="text-xs text-slate-500">Trạng thái</p><div className="mt-2"><StatusBadge value={data.status}/></div></div><div className="surface-card p-4"><p className="text-xs text-slate-500">Lệnh dịch vụ</p><p className="mt-1 text-2xl font-black">{data.serviceOrders.length}</p></div><div className="surface-card p-4"><p className="text-xs text-slate-500">Ticket</p><p className="mt-1 text-2xl font-black">{data.supportTickets.length}</p></div><div className="surface-card p-4"><p className="text-xs text-slate-500">Đối soát</p><p className="mt-1 text-2xl font-black">{data.paymentBatches.length}</p></div></section>
    <form onSubmit={save} className="surface-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="page-section-title">Xem / sửa thông tin đăng ký</h2><p className="page-section-subtitle">Đổi mã đại lý sẽ đồng bộ mã trên toàn bộ tài khoản Đại lý/KTV liên quan.</p></div><button disabled={saving} className="btn-primary px-5 py-3 font-black text-white disabled:opacity-60">{saving ? "Đang lưu..." : "Lưu thay đổi"}</button></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{field("dealerCode", "Mã đại lý / mã CRM")}{field("name", "Tên đại lý / công ty")}{field("representativeName", "Người đại diện")}{field("phone", "Số điện thoại")}{field("email", "Email", "email")}{field("registrationType", "Loại đăng ký")}{field("province", "Tỉnh/Thành")}{field("address", "Địa chỉ")}{field("serviceArea", "Khu vực phụ trách")}{field("technicianCount", "Số kỹ thuật viên", "number")}{field("taxCode", "Mã số thuế")}{field("citizenId", "CCCD")}{field("bankAccount", "Số tài khoản")}{field("accountHolder", "Chủ tài khoản")}{field("bankName", "Ngân hàng")}</div><label className="mt-4 block"><span className="mb-1 block text-sm font-bold">Năng lực dịch vụ</span><textarea value={String(form.services ?? "")} onChange={(event) => setForm({ ...form, services: event.target.value })}/></label></form>
    <section className="grid gap-6 xl:grid-cols-2"><article className="surface-card"><div className="data-toolbar"><h2 className="page-section-title">Lệnh dịch vụ gần nhất</h2></div><div className="divide-y">{data.serviceOrders.slice(0, 20).map((order) => <div key={order.id} className="p-4"><div className="flex justify-between gap-2"><strong>{order.orderCode}</strong><StatusBadge value={order.status}/></div><p className="mt-1 text-sm text-slate-600">{order.customerName} · {order.serviceType}</p></div>)}{!data.serviceOrders.length && <p className="p-5 text-sm text-slate-500">Chưa có lệnh.</p>}</div></article><article className="surface-card"><div className="data-toolbar"><h2 className="page-section-title">Yêu cầu liên quan</h2></div><div className="divide-y">{data.supportTickets.slice(0, 20).map((ticket) => <div key={ticket.id} className="p-4"><div className="flex justify-between gap-2"><strong>{ticket.ticketCode}</strong><StatusBadge value={ticket.status}/></div><p className="mt-1 text-sm text-slate-600">{ticket.subject}</p></div>)}{!data.supportTickets.length && <p className="p-5 text-sm text-slate-500">Chưa có ticket.</p>}</div></article></section>
  </>}</div></main>;
}
