import Link from "next/link";
import { CONSUMABLE_PRODUCTS, PRODUCTS } from "@/data/products";
import { Brand } from "@/components/ui/Brand";
import { Icon, type IconName } from "@/components/ui/Icon";

const serviceLinks: { href: string; label: string; description: string; icon: IconName }[] = [
  { href: "/scan", label: "Quét QR thiết bị", description: "Mở camera hoặc chọn ảnh QR", icon: "camera" },
  { href: "/login", label: "Đăng nhập theo vị trí", description: "Khách, Admin, CSKH hoặc đại lý", icon: "lock" },
  { href: "/customer-portal", label: "Cổng khách hàng", description: "Xem máy, lịch bảo trì và gửi SOS", icon: "user" },
  { href: "/dealer-register", label: "Đăng ký đại lý / CTV", description: "Gia nhập mạng lưới kỹ thuật KOSOVOTA", icon: "users" },
];

const operationCards: { href: string; title: string; text: string; icon: IconName }[] = [
  { href: "/login", title: "Vào hệ thống", text: "Chọn vị trí trước khi đăng nhập để tránh vào nhầm quyền.", icon: "shield" },
  { href: "/customer-portal", title: "Tra cứu máy", text: "Khách hàng xác thực OTP để xem bảo hành, lịch và SOS.", icon: "qr" },
  { href: "/dealer-register", title: "Đăng ký đại lý", text: "Thu thập hồ sơ kỹ thuật, khu vực phục vụ và năng lực kho.", icon: "store" },
  { href: "/contact", title: "Tư vấn nhanh", text: "Gửi nhu cầu lắp đặt, thay lõi hoặc triển khai hệ thống lọc.", icon: "send" },
];

export default function HomePage() {
  return <main className="min-h-screen bg-[#f5f8f7] text-slate-950">
    <header className="sticky top-0 z-40 border-b border-emerald-950/10 bg-white/90 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6"><Brand/><nav className="hidden items-center gap-1 rounded-2xl bg-slate-100/80 p-1 text-sm font-bold text-slate-600 md:flex"><a href="#san-pham" className="rounded-xl px-4 py-2.5 hover:bg-white hover:text-emerald-700">Sản phẩm</a><a href="#dich-vu" className="rounded-xl px-4 py-2.5 hover:bg-white hover:text-emerald-700">Dịch vụ</a><Link href="/contact" className="rounded-xl px-4 py-2.5 hover:bg-white hover:text-emerald-700">Tư vấn</Link></nav><Link href="/login" className="btn-primary inline-flex items-center gap-2 px-4 py-2.5 text-sm font-extrabold text-white"><Icon name="lock" size={17}/> Đăng nhập</Link></div>
    </header>

    <section className="relative isolate overflow-hidden bg-[linear-gradient(135deg,#041f19_0%,#064e3b_52%,#0f766e_100%)] text-white">
      <div className="absolute -left-32 top-24 h-72 w-72 rounded-full bg-emerald-400/15 blur-3xl"/><div className="absolute -right-20 -top-24 h-96 w-96 rounded-full bg-cyan-300/10 blur-3xl"/>
      <div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:py-28">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-extrabold uppercase tracking-[.18em] text-emerald-200"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_0_5px_rgba(52,211,153,.12)]"/> Hệ sinh thái dịch vụ sau bán hàng</div><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.12] tracking-[-.05em] sm:text-6xl lg:text-[4.5rem]">Trung tâm vận hành <span className="text-emerald-300">máy lọc nước, khách hàng và dịch vụ.</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-emerald-50/75 sm:text-lg">Ưu tiên các luồng quan trọng: đăng nhập đúng vị trí, tra cứu khách hàng, quản lý máy, điều phối kỹ thuật, kho vật tư và báo cáo sau bán hàng.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-3.5 font-extrabold text-emerald-950 shadow-xl hover:-translate-y-0.5"><Icon name="lock" size={19}/> Đăng nhập theo vị trí</Link><Link href="/customer-portal" className="inline-flex items-center gap-2 rounded-2xl border border-white/20 bg-white/10 px-6 py-3.5 font-extrabold text-white backdrop-blur hover:bg-white/15"><Icon name="user" size={19}/> Cổng khách hàng</Link></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-4 text-sm text-white/70">{["QR bảo hành điện tử","Nhắc lịch tự động","Điều phối theo GPS"].map((item)=><span key={item} className="inline-flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-full bg-emerald-400/20 text-emerald-300"><Icon name="check" size={14}/></span>{item}</span>)}</div></div>
        <div className="relative mx-auto w-full max-w-lg"><div className="glass-card relative overflow-hidden rounded-[2rem] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-emerald-300">KOSOVOTA SERVICE CLOUD</p><h2 className="mt-2 text-xl font-extrabold">Một nền tảng vận hành thống nhất</h2></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-400 text-emerald-950"><Icon name="activity" size={24}/></span></div><div className="mt-6 grid grid-cols-2 gap-3">{[["qr","QR định danh","Kích hoạt & bảo hành"],["map-pin","GPS","Vị trí máy chính xác"],["alert","SOS 24/7","Tiếp nhận sự cố"],["calendar","CSOS","Nhắc lịch chăm sóc"]].map(([icon,title,text])=><div key={title} className="rounded-2xl border border-white/10 bg-slate-950/25 p-4"><Icon name={icon as IconName} className="text-emerald-300"/><p className="mt-4 font-extrabold">{title}</p><p className="mt-1 text-xs leading-5 text-white/55">{text}</p></div>)}</div><div className="mt-3 flex items-center gap-3 rounded-2xl bg-emerald-400 p-4 text-emerald-950"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white/70"><Icon name="route" size={22}/></span><div><p className="text-xs font-bold uppercase tracking-wider opacity-65">Luồng dữ liệu liên thông</p><p className="font-extrabold">Máy · Khách hàng · Đại lý · Dịch vụ</p></div></div></div></div>
      </div>
    </section>

    <section className="relative z-10 -mt-10 mx-auto max-w-7xl px-4 sm:px-6">
      <div className="grid gap-4 rounded-[2rem] border border-slate-200 bg-white p-4 shadow-[0_20px_70px_rgba(15,23,42,.12)] md:grid-cols-4">
        {operationCards.map((item)=><Link key={item.href} href={item.href} className="group rounded-3xl border border-slate-100 bg-slate-50 p-5 hover:-translate-y-1 hover:border-emerald-200 hover:bg-emerald-50">
          <span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-emerald-700 shadow-sm"><Icon name={item.icon} size={23}/></span>
          <strong className="mt-4 block text-slate-950">{item.title}</strong>
          <span className="mt-2 block text-sm leading-6 text-slate-600">{item.text}</span>
          <span className="mt-4 inline-flex items-center gap-1 text-sm font-extrabold text-emerald-700">Mở mục này <Icon name="chevron-right" size={15} className="transition group-hover:translate-x-1"/></span>
        </Link>)}
      </div>
    </section>

    <section id="san-pham" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl"><p className="text-xs font-extrabold uppercase tracking-[.22em] text-emerald-700">Danh mục sản phẩm</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-5xl">Giải pháp phù hợp cho từng nhu cầu</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Mỗi cấu hình được đồng bộ sẵn với chu kỳ bảo trì, vật tư và quy trình chăm sóc riêng.</p></div><Link href="/contact" className="btn-secondary self-start"><Icon name="send" size={18}/> Yêu cầu tư vấn</Link></div><div className="mt-10 grid gap-5 md:grid-cols-2">{PRODUCTS.map((product)=><article key={product.slug} className="group overflow-hidden rounded-[1.65rem] border border-slate-200/80 bg-white shadow-[0_12px_40px_rgba(15,23,42,.06)] hover:-translate-y-1 hover:shadow-[0_22px_60px_rgba(15,23,42,.12)]"><div className={`relative overflow-hidden bg-gradient-to-br ${product.accent} p-7 text-white`}><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-white/10"/><div className="relative flex items-start justify-between"><span className="grid h-16 w-16 place-items-center rounded-2xl border border-white/15 bg-white/10 backdrop-blur"><Icon name={product.icon} size={31}/></span><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[11px] font-extrabold uppercase tracking-wider">{product.category}</span></div><h3 className="relative mt-7 text-2xl font-black">{product.name}</h3><p className="relative mt-3 max-w-xl leading-7 text-white/75">{product.tagline}</p></div><div className="p-7"><ul className="space-y-3">{product.highlights.map((item)=><li key={item} className="flex gap-3 text-sm text-slate-600"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Icon name="check" size={13}/></span>{item}</li>)}</ul><div className="mt-7 flex flex-wrap gap-3"><Link href={`/products/${product.slug}`} className="btn-primary inline-flex items-center gap-2 px-5 py-3 text-sm font-extrabold text-white">Xem chi tiết <Icon name="chevron-right" size={17}/></Link><Link href={`/contact?product=${product.slug}`} className="btn-secondary text-sm">Nhận tư vấn</Link></div></div></article>)}</div></section>

    <section className="border-y border-slate-200/80 bg-white"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="grid gap-5 md:grid-cols-2">{CONSUMABLE_PRODUCTS.map((product)=><article key={product.slug} className="flex gap-5 rounded-3xl border border-slate-200 bg-[#f8fbfa] p-6"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-white text-emerald-700 shadow-sm"><Icon name={product.icon} size={28}/></span><div><p className="text-[11px] font-extrabold uppercase tracking-[.16em] text-emerald-700">{product.category}</p><h3 className="mt-1 text-xl font-extrabold">{product.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{product.description}</p></div></article>)}</div></div></section>

    <section id="dich-vu" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-extrabold uppercase tracking-[.22em] text-emerald-700">Dịch vụ sau bán hàng</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-4xl">Không để khách hàng tự nhớ lịch thay lõi.</h2><p className="mt-4 leading-7 text-slate-600">Hệ thống tự sinh lịch theo dòng máy, cảnh báo CSKH, tìm kỹ thuật viên phù hợp và lưu báo cáo xác thực sau mỗi lần phục vụ.</p></div><div className="grid gap-4 sm:grid-cols-3">{[["calendar","Nhắc lịch tự động","Tạo các mốc 3–5 ngày, 1, 3, 6, 9, 12 và 24 tháng."],["map-pin","Điều phối gần nhất","Xếp hạng đại lý theo khoảng cách và đúng năng lực."],["camera","Báo cáo xác thực","Lưu ảnh lõi cũ, lõi mới, máy hoàn thành và chữ ký."]].map(([icon,title,text])=><article key={title} className="rounded-3xl bg-slate-950 p-6 text-white shadow-xl"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-400/15 text-emerald-300"><Icon name={icon as IconName} size={23}/></span><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{text}</p></article>)}</div></div></section>

    <section className="bg-emerald-800 text-white"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{serviceLinks.map((item)=><Link key={item.href} href={item.href} className="group flex items-center gap-4 rounded-2xl border border-white/12 bg-white/8 p-5 hover:-translate-y-0.5 hover:bg-white/14"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/10 text-emerald-200"><Icon name={item.icon} size={23}/></span><span><strong className="block">{item.label}</strong><span className="mt-1 block text-xs leading-5 text-white/55">{item.description}</span></span><Icon name="chevron-right" className="ml-auto text-white/50 group-hover:translate-x-1 group-hover:text-white"/></Link>)}</div></div></section>
    <footer className="bg-slate-950 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-8 text-sm sm:px-6 md:flex-row md:items-center md:justify-between"><Brand inverse/><div className="flex flex-wrap gap-x-6 gap-y-2"><span className="inline-flex items-center gap-2"><Icon name="phone" size={16}/> Hotline: 1900 633 029</span><span>© 2026 KOSOVOTA</span></div></div></footer>
  </main>;
}
