"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { PortalHeader } from "@/components/ui/PortalHeader";
import { MetricCard } from "@/components/ui/MetricCard";
import { LoadingState } from "@/components/ui/LoadingState";
import { Notice } from "@/components/ui/Notice";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { Icon } from "@/components/ui/Icon";

type Batch={id:string;batchCode:string;status:string;periodStart:string;periodEnd:string;netAmount:number;bankReference?:string|null;lines:{id:string;totalAmount:number;serviceOrder:{orderCode:string;serviceType:string}}[]};type Data={batches:Batch[];summary:{total:number;paid:number;pending:number}};
const money=(v=0)=>new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(v);const date=(v:string)=>new Intl.DateTimeFormat("vi-VN",{dateStyle:"short"}).format(new Date(v));
export default function DealerPaymentsPage(){const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");useEffect(()=>{fetch("/api/payments",{cache:"no-store"}).then(r=>r.json().then(j=>({r,j}))).then(({r,j})=>{if(!r.ok||!j.success)throw new Error(j.message);setData(j.data)}).catch(e=>setError(e.message));},[]);return <main className="min-h-screen"><PortalHeader title="Đối soát thu nhập" subtitle="Theo dõi công dịch vụ đã duyệt và thanh toán" homeHref="/agent-portal" homeLabel="Lệnh dịch vụ" onLogout={()=>fetch("/api/auth/logout",{method:"POST"}).then(()=>location.assign("/login"))}><Link href="/agent-portal" className="btn-secondary"><Icon name="wrench" size={16}/>Lệnh dịch vụ</Link><Link href="/agent-portal/inventory" className="btn-secondary"><Icon name="package" size={16}/>Kho</Link></PortalHeader><div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">{error&&<Notice kind="error">{error}</Notice>}{!data?<LoadingState label="Đang tải đối soát..."/>:<><section className="grid gap-3 sm:grid-cols-3"><MetricCard label="Tổng thu nhập" value={money(data.summary.total)} icon="wallet" tone="violet"/><MetricCard label="Đã thanh toán" value={money(data.summary.paid)} icon="check" tone="emerald"/><MetricCard label="Đang chờ" value={money(data.summary.pending)} icon="clock" tone="amber"/></section><section className="surface-card"><div className="data-toolbar"><div><h2 className="page-section-title">Lịch sử đối soát</h2><p className="page-section-subtitle">Chi tiết từng kỳ và từng lệnh dịch vụ</p></div></div><div className="divide-y">{data.batches.map(b=><details key={b.id} className="group p-5"><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3"><div><p className="font-black">{b.batchCode}</p><p className="text-sm text-slate-500">{date(b.periodStart)} – {date(b.periodEnd)} · {b.lines.length} lệnh</p></div><div className="flex items-center gap-3"><strong className="text-emerald-700">{money(b.netAmount)}</strong><StatusBadge value={b.status}/></div></summary><div className="mt-4 overflow-hidden rounded-2xl border"><table className="min-w-full text-sm"><thead><tr><th className="p-3 text-left">Mã lệnh</th><th className="p-3 text-left">Dịch vụ</th><th className="p-3 text-right">Thành tiền</th></tr></thead><tbody>{b.lines.map(l=><tr key={l.id}><td className="p-3 font-bold">{l.serviceOrder.orderCode}</td><td className="p-3">{l.serviceOrder.serviceType}</td><td className="p-3 text-right font-black">{money(l.totalAmount)}</td></tr>)}</tbody></table></div>{b.bankReference&&<p className="mt-3 text-sm text-slate-500">Mã giao dịch: <strong>{b.bankReference}</strong></p>}</details>)}{!data.batches.length&&<p className="p-10 text-center text-slate-500">Chưa có kỳ đối soát.</p>}</div></section></>}</div></main>}
