"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { OperationsHeader } from "@/components/ui/OperationsHeader";
import { MetricCard } from "@/components/ui/MetricCard";
import { Notice } from "@/components/ui/Notice";
import { LoadingState } from "@/components/ui/LoadingState";
import { Icon } from "@/components/ui/Icon";
import { StatusBadge } from "@/components/ui/StatusBadge";

type Dealer={id:string;dealerCode:string;name:string;bankAccount?:string|null;accountHolder?:string|null;bankName?:string|null};
type Line={id:string;totalAmount:number;serviceAmount:number;materialAmount:number;serviceOrder:{orderCode:string;serviceType:string;updatedAt:string}};
type Batch={id:string;batchCode:string;status:string;periodStart:string;periodEnd:string;grossAmount:number;deductions:number;netAmount:number;bankReference?:string|null;createdAt:string;dealer:Dealer;lines:Line[]};
type Order={id:string;dealerId?:string|null;serviceFee?:number|null;dealer?:Dealer|null};
type Data={batches:Batch[];eligibleOrders:Order[];dealers:Dealer[];summary:{total:number;paid:number;pending:number}};
const money=(v=0)=>new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(v);
const date=(v:string)=>new Intl.DateTimeFormat("vi-VN",{dateStyle:"short"}).format(new Date(v));

export default function PaymentsPage(){
 const [data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[error,setError]=useState("");const[open,setOpen]=useState(false);
 const now=new Date();const first=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10);const last=new Date(now.getFullYear(),now.getMonth()+1,0).toISOString().slice(0,10);
 const[form,setForm]=useState({dealerId:"",periodStart:first,periodEnd:last,note:""});
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/payments",{cache:"no-store"});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message);setData(j.data);if(!form.dealerId&&j.data.dealers[0])setForm(c=>({...c,dealerId:j.data.dealers[0].id}));}catch(e){setError(e instanceof Error?e.message:"Không tải được đối soát");}finally{setLoading(false);}},[form.dealerId]);useEffect(()=>{void load();},[load]);
 const eligible=useMemo(()=>data?.eligibleOrders.filter(o=>o.dealerId===form.dealerId).length||0,[data,form.dealerId]);
 async function create(e:FormEvent){e.preventDefault();setError("");const r=await fetch("/api/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok||!j.success){setError(j.message||"Không tạo được đối soát");return;}setMessage(j.message);setOpen(false);await load();}
 async function update(id:string,status:string){const bankReference=status==="PAID"?prompt("Nhập mã giao dịch ngân hàng")||"":undefined;const r=await fetch(`/api/payments/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,bankReference})});const j=await r.json();if(!r.ok||!j.success){setError(j.message);return;}setMessage(j.message);await load();}
 return <main className="min-h-screen"><OperationsHeader title="Đối soát đại lý" subtitle="Tập hợp lệnh hoàn thành, duyệt công và theo dõi thanh toán" actions={<button type="button" onClick={load} className="icon-button"><Icon name="refresh" size={18}/></button>}/><div className="page-container space-y-6">{message&&<Notice kind="success">{message}</Notice>}{error&&<Notice kind="error">{error}</Notice>}{loading&&!data?<LoadingState label="Đang tải dữ liệu đối soát..."/>:data&&<>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Tổng giá trị đối soát" value={money(data.summary.total)} icon="wallet" tone="violet"/><MetricCard label="Đã thanh toán" value={money(data.summary.paid)} icon="check" tone="emerald"/><MetricCard label="Chờ xử lý" value={money(data.summary.pending)} icon="clock" tone="amber"/><MetricCard label="Lệnh đủ điều kiện" value={data.eligibleOrders.length} icon="file" tone="blue"/></section>
 <section className="surface-card"><div className="data-toolbar"><div><h2 className="page-section-title">Các kỳ đối soát</h2><p className="page-section-subtitle">Mỗi lệnh dịch vụ chỉ được xuất hiện trong một kỳ</p></div><button type="button" onClick={()=>setOpen(true)} className="btn-primary inline-flex items-center gap-2 px-4 py-3 font-black text-white"><Icon name="plus" size={17}/>Tạo kỳ đối soát</button></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr>{["Mã kỳ","Đại lý","Thời gian","Số lệnh","Giá trị","Trạng thái","Ngân hàng","Thao tác"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{data.batches.map(b=><tr key={b.id}><td className="p-3 font-black">{b.batchCode}</td><td className="p-3"><strong>{b.dealer.name}</strong><div className="text-xs text-slate-500">{b.dealer.dealerCode}</div></td><td className="p-3">{date(b.periodStart)} – {date(b.periodEnd)}</td><td className="p-3 font-bold">{b.lines.length}</td><td className="p-3 font-black text-emerald-700">{money(b.netAmount)}</td><td className="p-3"><StatusBadge value={b.status}/></td><td className="p-3 text-xs">{b.bankReference||b.dealer.bankName||"—"}</td><td className="p-3"><div className="flex gap-2">{b.status==="SUBMITTED"&&<button type="button" onClick={()=>update(b.id,"APPROVED")} className="btn-secondary px-3 py-2 text-xs">Duyệt</button>}{b.status==="APPROVED"&&<button type="button" onClick={()=>update(b.id,"PAID")} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Thanh toán</button>}{["SUBMITTED","APPROVED"].includes(b.status)&&<button type="button" onClick={()=>update(b.id,"REJECTED")} className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">Từ chối</button>}</div></td></tr>)}{!data.batches.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">Chưa có kỳ đối soát.</td></tr>}</tbody></table></div></section>
 </>}</div>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={create} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-xl font-black">Tạo kỳ đối soát</h3><p className="mt-1 text-sm text-slate-500">Hệ thống tự lấy lệnh hoàn thành chưa thanh toán</p></div><button type="button" onClick={()=>setOpen(false)} className="icon-button"><Icon name="x" size={18}/></button></div><div className="space-y-4"><label className="block"><span className="mb-1 block text-sm font-bold">Đại lý</span><select value={form.dealerId} onChange={e=>setForm({...form,dealerId:e.target.value})}>{data?.dealers.map(d=><option key={d.id} value={d.id}>{d.dealerCode} · {d.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-sm font-bold">Từ ngày</span><input type="date" value={form.periodStart} onChange={e=>setForm({...form,periodStart:e.target.value})}/></label><label><span className="mb-1 block text-sm font-bold">Đến ngày</span><input type="date" value={form.periodEnd} onChange={e=>setForm({...form,periodEnd:e.target.value})}/></label></div><Notice kind="info">Có {eligible} lệnh đang đủ điều kiện cho đại lý đã chọn.</Notice><label className="block"><span className="mb-1 block text-sm font-bold">Ghi chú</span><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><button className="btn-primary w-full p-3 font-black text-white">Tạo và gửi duyệt</button></div></form></div>}</main>;
}
